name: lesson

version: 1.0.0

dependencies:
  ## Replace flutter SDK dependency with flutter_web
  #flutter:
  #  sdk: flutter
  flutter_web: any

dev_dependencies:
  ## Similarly replace test libraries to web test libraries
  #flutter_test:
  #  sdk: flutter
  flutter_web_test: any

  ## Add these dependencies to enable the Dart web build system
  build_runner: any
  build_web_compilers: any

  test: ^1.3.4

## Assets are handled differenly in web. So remove them from here
# flutter:
#   uses-material-design: true
#   assets:
#     - asset/
#
#   fonts:
#   - family: Plaster
#     fonts:
#     - asset: asset/fonts/plaster/Plaster-Regular.ttf

## Add the following:
## flutter_web packages are not published to pub.dartlang.org
## These overrides tell the package tools to get them from GitHub
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
